export default {
    GET_ACTIONS_BY_USER_REQUEST: 'GET_ACTIONS_BY_USER_REQUEST',
    GET_ACTIONS_BY_USER_SUCCESS: 'GET_ACTIONS_BY_USER_SUCCESS',
    GET_ACTIONS_BY_USER_FAIL: 'GET_ACTIONS_BY_USER_FAIL',

    GET_ACTIONS_BY_TASK_REQUEST: 'GET_ACTIONS_BY_TASK_REQUEST',
    GET_ACTIONS_BY_TASK_SUCCESS: 'GET_ACTIONS_BY_TASK_SUCCESS',
    GET_ACTIONS_BY_TASK_FAIL: 'GET_ACTIONS_BY_TASK_FAIL',

    UPDATE_ACTION_REQUEST: 'UPDATE_ACTION_REQUEST',
    UPDATE_ACTION_SUCCESS: 'UPDATE_ACTION_SUCCESS',
    UPDATE_ACTION_FAIL: 'UPDATE_ACTION_FAIL',
}