export default {
    CREATE_FILE_REQUEST: 'CREATE_FILE_REQUEST',
    CREATE_FILE_SUCCESS: 'CREATE_FILE_SUCCESS',
    CREATE_FILE_FAIL: 'CREATE_FILE_FAIL',

    DELETE_FILE_REQUEST: 'DELETE_FILE_REQUEST',
    DELETE_FILE_SUCCESS: 'DELETE_FILE_SUCCESS',
    DELETE_FILE_FAIL: 'DELETE_FILE_FAIL',
}