export default {
    GET_PROJECT_TYPES_REQUEST: 'GET_PROJECT_TYPES_REQUEST',
    GET_PROJECT_TYPES_SUCCESS: 'GET_PROJECT_TYPES_SUCCESS',
    GET_PROJECT_TYPES_FAIL: 'GET_PROJECT_TYPES_FAIL',

    UPDATE_PROJECT_TYPE_REQUEST: 'UPDATE_PROJECT_TYPE_REQUEST',
    UPDATE_PROJECT_TYPE_SUCCESS: 'UPDATE_PROJECT_TYPE_SUCCESS',
    UPDATE_PROJECT_TYPE_FAIL: 'UPDATE_PROJECT_TYPE_FAIL',

    ADD_PROJECT_TYPE_REQUEST: 'ADD_PROJECT_TYPE_REQUEST',
    ADD_PROJECT_TYPE_SUCCESS: 'ADD_PROJECT_TYPE_SUCCESS',
    ADD_PROJECT_TYPE_FAIL: 'ADD_PROJECT_TYPE_FAIL',

    DELETE_PROJECT_TYPE_REQUEST: 'DELETE_PROJECT_TYPE_REQUEST',
    DELETE_PROJECT_TYPE_SUCCESS: 'DELETE_PROJECT_TYPE_SUCCESS',
    DELETE_PROJECT_TYPE_FAIL: 'DELETE_PROJECT_TYPE_FAIL',
}