export default {
    CREATE_SPRINT_REQUEST: 'CREATE_SPRINT_REQUEST',
    CREATE_SPRINT_SUCCESS: 'CREATE_SPRINT_SUCCESS',
    CREATE_SPRINT_FAIL: 'CREATE_SPRINT_FAIL',

    UPDATE_SPRINT_REQUEST: 'UPDATE_SPRINT_REQUEST',
    UPDATE_SPRINT_SUCCESS: 'UPDATE_SPRINT_SUCCESS',
    UPDATE_SPRINT_FAIL: 'UPDATE_SPRINT_FAIL',

    COMPLETE_SPRINT_REQUEST: 'COMPLETE_SPRINT_REQUEST',
    COMPLETE_SPRINT_SUCCESS: 'COMPLETE_SPRINT_SUCCESS',
    COMPLETE_SPRINT_FAIL: 'COMPLETE_SPRINT_FAIL',
}