export default {
    GET_TASKS_REQUEST: 'GET_TASKS_REQUEST',
    GET_TASKS_SUCCESS: 'GET_TASKS_SUCCESS',
    GET_TASKS_FAIL: 'GET_TASKS_FAIL',

    SEARCH_TASKS_REQUEST: 'SEARCH_TASKS_REQUEST',
    SEARCH_TASKS_SUCCESS: 'SEARCH_TASKS_SUCCESS',
    SEARCH_TASKS_FAIL: 'SEARCH_TASKS_FAIL',

    GET_TASK_REQUEST: 'GET_TASK_REQUEST',
    GET_TASK_SUCCESS: 'GET_TASK_SUCCESS',
    GET_TASK_FAIL: 'GET_TASK_FAIL',

    CREATE_TASK_REQUEST: 'CREATE_TASK_REQUEST',
    CREATE_TASK_SUCCESS: 'CREATE_TASK_SUCCESS',
    CREATE_TASK_FAIL: 'CREATE_TASK_FAIL',

    UPDATE_TASK_REQUEST: 'UPDATE_TASK_REQUEST',
    UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
    UPDATE_TASK_FAIL: 'UPDATE_TASK_FAIL',

    UPDATE_ORDER_TASK_REQUEST: 'UPDATE_ORDER_TASK_REQUEST',
    UPDATE_ORDER_TASK_SUCCESS: 'UPDATE_ORDER_TASK_SUCCESS',
    UPDATE_ORDER_TASK_FAIL: 'UPDATE_ORDER_TASK_FAIL',

    DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
    DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',
    DELETE_TASK_FAIL: 'DELETE_TASK_FAIL',
}